name: Github Actions for Main Branch
on:
  push:
    branches: 
      - main
jobs:
  Test:
    runs-on: "ubuntu-latest"
    steps: 
        - name: Checkout code
          uses: actions/checkout@v4
        - name: echo Message
          run: echo "Hello Github action"
        - name: Show file in directory
          run: ls -al

